spring.application.name=pipelineiq-backend
server.port=8081

# ===== MONGODB =====
spring.data.mongodb.uri=mongodb://localhost:27017/pipelineiq
spring.data.mongodb.database=pipelineiq

# ===== JENKINS =====
jenkins.url=http://localhost:8080
jenkins.username=admin
jenkins.token=117bb61af2f182c724568cf38b05b733bc
jenkins.sync.interval=30000

# ===== CORS =====
cors.allowed-origins=http://localhost:5173

# ===== ACTUATOR / PROMETHEUS =====
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always


# Replace with your own Gmail + App Password
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cybersharma073@gmail.com
spring.mail.password=apxzdsjnlclknmba 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
alert.email.to=YOUR_TEAM_EMAIL@gmail.com

# ===== LOGGING =====
logging.level.com.pipelineiq=INFO