spring.application.name=pipelineiq-backend
server.port=8081

# ===== MONGODB =====
spring.data.mongodb.uri=
spring.data.mongodb.database=

# ===== JENKINS =====
jenkins.url=http://localhost:8080
jenkins.username=
jenkins.token=
jenkins.sync.interval=

# ===== CORS =====
cors.allowed-origins=http://localhost:5173

# ===== ACTUATOR / PROMETHEUS =====
management.endpoints.web.exposure.include=
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always


# Replace with your own Gmail + App Password
spring.mail.host=smtp.gmail.com
spring.mail.port=
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
alert.email.to=

# ===== LOGGING =====
logging.level.com.pipelineiq=INFO
